spec: add support for koji 8.4 build
C2Devel/psh pull request #1
Opened 2022-11-09 15:43 UTC by Sharpeye90

2023-01-14 15:19 UTC, odivlad requested changes

2023-01-14 15:19 UTC, odivlad commented on Makefile
> +VERSION  := $(shell rpm -q --qf "%{version}\n" --specfile $(RPM_NAME).spec | head -1)
кажется, что делать жесткую привязку наличия rpm на системе, чтобы делать даже не rpm-related вещи, не лучшая идея.

2023-01-24 19:08 UTC, Sharpeye90 commented on Makefile
> +VERSION  := $(shell rpm -q --qf "%{version}\n" --specfile $(RPM_NAME).spec | head -1)
fixed

2023-01-24 19:52 UTC, odivlad approved these changes

2023-01-24 19:53 UTC, merged